_commit: 0.8.0
_src_path: gh:selrahcd/copier-php-kata
include_docker: true
include_sample_test: true
include_tcr_script: false
kata_name: PasswordValidation
tell_about_test_run_logger: false
test_run_logger: false
